#!/usr/bin/env bash
#
# bootstrap.sh — lay down the plugin-factory skeleton in an empty repo.
# Run once from the repo root:   bash bootstrap.sh
#
# Creates: root CMakeLists.txt (fetches JUCE 8), a shared header-only core/,
# a CMake helper that reads the version from each plugin.toml, README with the
# catalog markers, roadmap.toml, tools/gen_catalog.py, and .gitignore.
# It does NOT create a plugin — that's the kickoff task's job.

set -euo pipefail

mkdir -p cmake core/include/factory_core plugins tools
touch plugins/.gitkeep core/include/factory_core/.gitkeep

# ---------------------------------------------------------------- root CMake
cat > CMakeLists.txt << 'EOF'
cmake_minimum_required(VERSION 3.22)   # JUCE 8 requires CMake >= 3.22

project(PluginFactory VERSION 0.1.0 LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  set(CMAKE_BUILD_TYPE Release CACHE STRING "" FORCE)
endif()

list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
include(FactoryHelpers)

# --- JUCE (pinned; bump to the latest 8.0.x as you like) ---
include(FetchContent)
FetchContent_Declare(JUCE
  GIT_REPOSITORY https://github.com/juce-framework/JUCE.git
  GIT_TAG        8.0.13
  GIT_SHALLOW    TRUE)
FetchContent_MakeAvailable(JUCE)

# --- Shared DSP core (header-only for now; plugins compose from this) ---
add_library(factory_core INTERFACE)
target_include_directories(factory_core INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/core/include)
target_compile_features(factory_core INTERFACE cxx_std_20)

enable_testing()

# --- Auto-include every plugins/<slug> that has a CMakeLists.txt ---
file(GLOB _plugin_dirs LIST_DIRECTORIES true ${CMAKE_CURRENT_SOURCE_DIR}/plugins/*)
foreach(_dir ${_plugin_dirs})
  if(IS_DIRECTORY ${_dir} AND EXISTS ${_dir}/CMakeLists.txt)
    add_subdirectory(${_dir})
  endif()
endforeach()
EOF

# ----------------------------------------------------- CMake version helper
cat > cmake/FactoryHelpers.cmake << 'EOF'
# factory_read_version(<toml_path> <out_var>)
# Extract  version = "X.Y.Z"  from a plugin.toml so the manifest is the single
# source of truth for the plugin's version (catalog == binary == release).
function(factory_read_version toml_path out_var)
  file(READ "${toml_path}" _toml)
  string(REGEX MATCH "version[ \t]*=[ \t]*\"([0-9]+\\.[0-9]+\\.[0-9]+)\"" _m "${_toml}")
  if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "No semantic version found in ${toml_path}")
  endif()
  set(${out_var} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()
EOF

# ----------------------------------------------------------------- README
cat > README.md << 'EOF'
# Plugin Factory

Autonomous audio-plugin factory built with JUCE 8 + CMake.
See `CLAUDE.md` for the conventions every change must follow.

## Plugin catalog

<!-- BEGIN:CATALOG -->
(generated by tools/gen_catalog.py — do not edit by hand)
<!-- END:CATALOG -->

## Build

    cmake -B build -DCMAKE_BUILD_TYPE=Release
    cmake --build build
    ctest --test-dir build --output-on-failure
EOF

# --------------------------------------------------------------- roadmap
cat > roadmap.toml << 'EOF'
# Planned plugins not yet started. One [[plugin]] block each. Example:
#
# [[plugin]]
# name      = "Bus Compressor"
# category  = "Dynamics"
# reference = "SSL G-series bus comp"
EOF

# --------------------------------------------------------------- .gitignore
cat > .gitignore << 'EOF'
/build/
build*/
.cache/
.DS_Store
*.user
EOF

# --------------------------------------------------- tools/gen_catalog.py
cat > tools/gen_catalog.py << 'PYEOF'
#!/usr/bin/env python3
"""
tools/gen_catalog.py — generate the README catalog from machine-readable sources.

Sources of truth (one item lives in exactly ONE of these):
  plugins/<slug>/plugin.toml   real plugins   (status: shipped | in-progress)
  roadmap.toml                 planned plugins not yet started

Rewrites only the block between:
  <!-- BEGIN:CATALOG -->  ...  <!-- END:CATALOG -->

Usage:
  python tools/gen_catalog.py            # rewrite README.md in place
  python tools/gen_catalog.py --check    # exit 1 if README is out of date (CI)

Requires Python 3.11+ (stdlib tomllib).
"""
from __future__ import annotations

import glob
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN:CATALOG -->"
END = "<!-- END:CATALOG -->"


def load_plugins():
    shipped, in_progress = [], []
    for path in sorted(glob.glob(str(ROOT / "plugins" / "*" / "plugin.toml"))):
        raw = tomllib.loads(Path(path).read_text(encoding="utf-8"))
        p = raw.get("plugin", raw)
        entry = {
            "name": p.get("name", "?"),
            "slug": p.get("slug", Path(path).parent.name),
            "category": p.get("category", "?"),
            "version": p.get("version", ""),
            "formats": ", ".join(p.get("formats", [])),
            "reference": p.get("reference", "—"),
            "status": p.get("status", "shipped"),
        }
        (shipped if entry["status"] == "shipped" else in_progress).append(entry)
    return shipped, in_progress


def load_roadmap():
    f = ROOT / "roadmap.toml"
    if not f.exists():
        return []
    raw = tomllib.loads(f.read_text(encoding="utf-8"))
    items = raw.get("plugin", [])
    return sorted(items, key=lambda x: (x.get("category", ""), x.get("name", "")))


def md_table(rows, cols):
    if not rows:
        return "_None yet._"
    head = "| " + " | ".join(label for _, label in cols) + " |"
    sep = "| " + " | ".join("---" for _ in cols) + " |"
    body = [
        "| " + " | ".join(str(r.get(key, "—") or "—") for key, _ in cols) + " |"
        for r in rows
    ]
    return "\n".join([head, sep, *body])


def render() -> str:
    shipped, in_progress = load_plugins()
    planned = load_roadmap()
    parts = []
    parts.append(f"### Shipped ({len(shipped)})\n")
    parts.append(md_table(shipped, [
        ("name", "Plugin"), ("category", "Category"), ("version", "Version"),
        ("formats", "Formats"), ("reference", "Reference"),
    ]))
    parts.append(f"\n\n### In progress ({len(in_progress)})\n")
    parts.append(md_table(in_progress, [
        ("name", "Plugin"), ("category", "Category"), ("reference", "Reference"),
    ]))
    parts.append(f"\n\n### Planned ({len(planned)})\n")
    parts.append(md_table(planned, [
        ("name", "Plugin"), ("category", "Category"), ("reference", "Reference"),
    ]))
    return "\n".join(parts)


def splice(readme_text: str, block: str) -> str:
    if BEGIN not in readme_text or END not in readme_text:
        raise SystemExit(
            f"README.md is missing the markers {BEGIN} / {END}."
        )
    pre = readme_text.split(BEGIN)[0]
    post = readme_text.split(END, 1)[1]
    return f"{pre}{BEGIN}\n\n{block}\n\n{END}{post}"


def main() -> None:
    check = "--check" in sys.argv
    current = README.read_text(encoding="utf-8")
    updated = splice(current, render())
    if check:
        if current != updated:
            print("README catalog is out of date. Run: python tools/gen_catalog.py")
            sys.exit(1)
        print("README catalog is up to date.")
        return
    if current != updated:
        README.write_text(updated, encoding="utf-8")
        print("README catalog updated.")
    else:
        print("README catalog already up to date.")


if __name__ == "__main__":
    main()
PYEOF

# Initialize the catalog section so the markers resolve to empty tables.
python3 tools/gen_catalog.py || true

echo
echo "Skeleton created. Next:"
echo "  1. Put CLAUDE.md at the repo root."
echo "  2. Verify it configures (this fetches JUCE, takes a minute):"
echo "       cmake -B build -DCMAKE_BUILD_TYPE=Release"
echo "  3. Paste the kickoff prompt into Claude Code."